### Registration

POST localhost:8080/api/users
Content-Type: application/json

{
  "user":{
    "username": "Jacob",
    "email": "jake@jake.jake",
    "password": "jakejake"
  }
}

### Authentication

POST localhost:8080/api/users/login
Content-Type: application/json

{
  "user":{
    "email": "jake@jake.jake",
    "password": "jakejake"
  }
}

### Get Current User

GET localhost:8080/api/user
Content-Type: application/json
Authorization: Token eyJhbGciOiJFQ0RILUVTIiwiZW5jIjoiQTEyOENCQy1IUzI1NiIsImtpZCI6bnVsbCwiY3R5IjoiSldUIiwiZXBrIjp7Imt0eSI6Ik9LUCIsImNydiI6IlgyNTUxOSIsIngiOiJfOUsxc0lBM2d2eG84R2dIQl9oeEFJeFhIS21Wb3JCeS1ITWJRTzFuem1ZIn19..FlEFHFvTcuARXsBIOa1sag.byZQ97iE4ZzAHAk5aUKyPjv-99UHRSu3olrKd-w-5Z3REGmL2I32zA8r_WfN9juYsLwKpay8YALyXrRfvM8IpxDRv0CHJBVpWsZaZUQ8kSsGpgOcwgwy1-zhcekGWgfVPbyl24VJaJ1QQ9kCvB8nxU4MGU-iyWY4zI0U4MTWy_zH4OTw7LUupF4debZUNEuZfa3mDcwX9_1Z06dyMvXDhKfKV9Rk-P-cPu2a1yTjPHpSPUIt7zjBOx2JvgbfC8nVCQ49IppXjTZz3UcqmjBQO2bYG0UPnZh5k1ZCF3VSKLWB-NAbJ82zxrQU57Jt1AgdOiQb07QiRMTNMvV_Ynt6sQ.pxSgBtrtTL_ZHH9yFg2IHQ
