### Registration

POST localhost:8080/api/users
Content-Type: application/json

{
  "user":{
    "username": "Jacob",
    "email": "jake@jake.jake",
    "password": "jakejake"
  }
}

### Authentication

POST localhost:8080/api/users/login
Content-Type: application/json

{
  "user":{
    "email": "jake@jake.jake",
    "password": "jakejake"
  }
}

### Get Current User

GET localhost:8080/api/user
Content-Type: application/json
Authorization: Token eyJhbGciOiJFQ0RILUVTIiwiZW5jIjoiQTEyOENCQy1IUzI1NiIsImtpZCI6bnVsbCwiY3R5IjoiSldUIiwiZXBrIjp7Imt0eSI6Ik9LUCIsImNydiI6IlgyNTUxOSIsIngiOiJTTTRQc0lUZ3oxRlVWOXluUG9wYVViTTdyTXFtYVRxZ1NBZEQyRkZkTnljIn19..ewumoOzvPUqQx3KmNTN0Eg.MKB2UTxksoK8_xyfVGXZ2bFupIc9ppHjKQq15BkBnLllxRJjRYBydSZaqPEHA-BRCnhIov7HLzQ_ICh4F5wccyn3qf_jKB36Yvaw5ogHGDZ5tCV8qKeAZdDiMj1h-e5RLkLgVVKGOyyRsfI3nhgKvnJZ3E_09by3G9LXb6Yh6CV_VSyN3LgtgGUBpI0TBfzwTZWO5yQrvaBR0dtAFYQfhp3GKubk0E89rk_2lSqxs6Z5KOjxDy75Xwdka0eIaXtjGv0Afa-H0z30niQP_8Q0pXyjFLF7P20PhL6Oe3gop8Tc7TBLEIJt_iEDfZGdHctUG_nsOosSfn6XFK-L5_2hlw.uNyOYwNY5u1YF80Uld33DQ

### Update User

PUT localhost:8080/api/user
Content-Type: application/json
Authorization: Token eyJhbGciOiJFQ0RILUVTIiwiZW5jIjoiQTEyOENCQy1IUzI1NiIsImtpZCI6bnVsbCwiY3R5IjoiSldUIiwiZXBrIjp7Imt0eSI6Ik9LUCIsImNydiI6IlgyNTUxOSIsIngiOiI2R2c2QlJXcjJTR0plZ1FXNnBoaFhiR2dRV0xHNU1Cck1SSERvM01IZnpVIn19..I6wt6MtDoRws5DrfzICmNw.AtZ-osA5htTSasoMTgnZo4E3A5sQXAlV8AFHQwpZccKppA_17Qq8dqdGvSEueOz_MlelhJzSmWiKezELPqg3V_NoybgNqzJHgvQuWeXmFPzrHdBZRbHzNK_xg-dJHLyK2qIpV67M6lejXW3KopSOg7307HBLJPaX0KdgacKU2oc6Tt-B4jDDVBwpDgmwLmL6gx7iHEU3dILhBfISL9K-CUKQ8WCc0KB4aN9kKufatKVMPfg4uKtLHHMxRtvAXI1PMCXgC2VkHI038Yf_YVaF87RkeljO79jjf8-zsYAAA_aL5GulzWONzS99hZuqwcNRLTcviI5kZl12o8z0g3Kz4w.jcQVAnnqKrhrgMETO-KdYw

{
  "user":{
    "email": "jake@jake.jake",
    "bio": "I like to skateboard",
    "image": "https://i.stack.imgur.com/xHWG8.jpg"
  }
}

### Get Profile with no Authentication

GET localhost:8080/api/profiles/Jacob
Content-Type: application/json

### Get Profile with Authentication

GET localhost:8080/api/profiles/Jacob
Content-Type: application/json
Authorization: Token eyJhbGciOiJFQ0RILUVTIiwiZW5jIjoiQTEyOENCQy1IUzI1NiIsImtpZCI6bnVsbCwiY3R5IjoiSldUIiwiZXBrIjp7Imt0eSI6Ik9LUCIsImNydiI6IlgyNTUxOSIsIngiOiI2R2c2QlJXcjJTR0plZ1FXNnBoaFhiR2dRV0xHNU1Cck1SSERvM01IZnpVIn19..I6wt6MtDoRws5DrfzICmNw.AtZ-osA5htTSasoMTgnZo4E3A5sQXAlV8AFHQwpZccKppA_17Qq8dqdGvSEueOz_MlelhJzSmWiKezELPqg3V_NoybgNqzJHgvQuWeXmFPzrHdBZRbHzNK_xg-dJHLyK2qIpV67M6lejXW3KopSOg7307HBLJPaX0KdgacKU2oc6Tt-B4jDDVBwpDgmwLmL6gx7iHEU3dILhBfISL9K-CUKQ8WCc0KB4aN9kKufatKVMPfg4uKtLHHMxRtvAXI1PMCXgC2VkHI038Yf_YVaF87RkeljO79jjf8-zsYAAA_aL5GulzWONzS99hZuqwcNRLTcviI5kZl12o8z0g3Kz4w.jcQVAnnqKrhrgMETO-KdYw
