### Create Article

POST {{host}}/api/articles
Content-Type: application/json
Authorization: Token eyJhbGciOiJFQ0RILUVTIiwiZW5jIjoiQTEyOENCQy1IUzI1NiIsImtpZCI6bnVsbCwiY3R5IjoiSldUIiwiZXBrIjp7Imt0eSI6Ik9LUCIsImNydiI6IlgyNTUxOSIsIngiOiJYS0RxQTNVTUY1R1d5SXV4djJraG9qWllPMUlBZ0JVZW5ZWWFoYlpSVmpjIn19..jV4YkVWSUTLC0IaTyvP8Rg.R1Kf9vyBHVMSkm-v_8DZuuh5Ok80xcQ_GVQde_QxV896TJdoWkFe9MaXvAFEqv7WwJlSYIVJHMrWmdUeTkPH5Nx7WjzLsiS2tNDvb_71nYDGOZ8BqxvnZWuE_ZbU1Lo5LjHNUIvqJjNDcwiLAbeY1SHIzygMO1JeqKEFITEGvM-Zfc29Rm0SsW_knJdUmNlZV2KEgkOHNHrVGXipXZ2sg4RAE-u0KWZ9jGJJnaKO1yvEvsf6CbnHsMP2qHOHod3_NUzeAj3SCq4PnZeO2Y6Q1Ht0GV150x7WjjBt-mR8F4Bd3suWNkd1PhBpRWkjtDiE8BbTgIEkLHOC8uwjV1enaw.FlByhn4JJ3LFjx8ZBTqqyg

{
  "article": {
    "title": "How to train your dragon",
    "description": "Ever wonder how?",
    "body": "You have to believe",
    "tagList": [
      "reactjs",
      "angularjs",
      "dragons"
    ]
  }
}

### List Articles with no query, no Authorization

GET {{host}}/api/articles

### List Articles with query (favorited), no Authorization

GET {{host}}/api/articles?favorited=Jacob3

### List Articles with query (tag), no Authorization

GET {{host}}/api/articles?tag=reactjs

### List Articles with no query, Authorization (author Jacob1)

GET {{host}}/api/articles
Authorization: Token eyJhbGciOiJFQ0RILUVTIiwiZW5jIjoiQTEyOENCQy1IUzI1NiIsImtpZCI6bnVsbCwiY3R5IjoiSldUIiwiZXBrIjp7Imt0eSI6Ik9LUCIsImNydiI6IlgyNTUxOSIsIngiOiJDWDFyZlRrLW45eVh1czVCckhyS3VJeGtZOWp4RmZlTU1mdV9Zd2RyZ3prIn19..Y-lan6sLx3zDyH2amPjG7A.9ep7zD1TWmQk90hUY3xAeVyzRJKu9nNfB8kACtgiYWIZ3e8pUvAYeHBY4h0s8EmhTIsaKXFkJ5z6fUWOmRVjCgn_IovoBLfrP_7ZWfpPOhtu2sa7v2Pt1kn_deNRdtTHuZCI1KEMqQGuAAvRCn_mF71BMSitN8zVVkLw7azr-gHRMOPP-IhxmeIbovAVpfrlNm17JQgHrmJwy3BJcDaQeOxLgK6zliss4-ujdbx0SWu2Xlvgf5ret3dAsFyaeSV4r0d5mk4s57dDn8jFQ5JGWFYB_Jz9kLLVJfqn5YRwGjXrVn19WE-IfP1HsYo11U2HA2jOOf6cD4Mt6yFtVqpEdA.YGAVv8otPhHowPSfQZAmEQ

### List Articles with query (favorited), Authorization (not author Jacob2)

GET {{host}}/api/articles?favorited=Jacob3
Authorization: Token eyJhbGciOiJFQ0RILUVTIiwiZW5jIjoiQTEyOENCQy1IUzI1NiIsImtpZCI6bnVsbCwiY3R5IjoiSldUIiwiZXBrIjp7Imt0eSI6Ik9LUCIsImNydiI6IlgyNTUxOSIsIngiOiI4b2syR0VRNzRBMDJGT3ZtaWl1ZTcyZEpLbXFNWXdpREoyUmRWSkstcVJZIn19..plHxLG3tC9Rw8d26t7GdgQ.nGyeNMFAwS3n1-CDwim465rHkRNi3-OL5RnR_gYNLeTaC0HyuoOhGepgaqA5y9E1LhhVqSq8wSH4T_oJ_jC6WQwitPbMC5ZycF2OJfUsOXIpHGln6K1ZZeQD26HKkxxo6tNO_-nndy3IAWtt9C_SqhUnvtoyaazGhkX-XSUc3sZCKyBAuER62jjR5XRlzAPJUwF9luCXvDmFRl8Rp6jC8DBTRe95cLf6BZaMj4VZt15QgqzqgVc15p1xgj6x1Tc_xVpqn-JPfvFhmoYufBvx1mTE4xjLWIbnhMSom5_ivdmn_zHGC6jp5LgRWfnOJP1jtwKJEspzDEYRuTfoMZM2Nw.7NILRkwLBQBplMqCqdPM_A
