### Create Article

POST {{host}}/api/articles
Content-Type: application/json
Authorization: Token eyJhbGciOiJFQ0RILUVTIiwiZW5jIjoiQTEyOENCQy1IUzI1NiIsImtpZCI6bnVsbCwiY3R5IjoiSldUIiwiZXBrIjp7Imt0eSI6Ik9LUCIsImNydiI6IlgyNTUxOSIsIngiOiJka2dtN2RueENodkNlRzVXa2wzSDZRbTVfMV96RDBGYkJaTm02SDhzQW5zIn19..lTvbzIqmBPkWapgSOQ7pjA.aBYiOeFsfzz1JjsarkqD2KuC9xL60AgbqJ0hi_Z0MZ94t2ldg43aBhCClXyqdwUfPVhnqKsLVWa0nyXlRAzb8UOt3pjMbwWoupKecMDwu8busBHefuPaHMqo_nf7JNOdeuaZYdudu8tWVKPERwo8AScVQcKDts5eu_I6SFxH8H-tgBdJbRGo52Z6eFXAnpQwkqSps79Z3Ujywap3k4lm26v-ioXcwjqLpSqvJGi7nc-ae5S-vekkS8z1rW07rk7ppB-rF6EEusk7eRPuC1BJORwPTcP-XMYBS6qGaNh28f1iUzdso6FyQphYpNkLaQuEYAmjxD5cRp6heIZCsnHNXg.WPpqeBUe18wn4UA_9PJaBg

{
  "article": {
    "title": "How to train your dragon",
    "description": "Ever wonder how?",
    "body": "You have to believe",
    "tagList": [
      "reactjs",
      "angularjs",
      "dragons"
    ]
  }
}

### List Articles

GET {{host}}/api/articles
Authorization: Token eyJhbGciOiJFQ0RILUVTIiwiZW5jIjoiQTEyOENCQy1IUzI1NiIsImtpZCI6bnVsbCwiY3R5IjoiSldUIiwiZXBrIjp7Imt0eSI6Ik9LUCIsImNydiI6IlgyNTUxOSIsIngiOiJnVWZSRHhCX2NHaUJTNVB1YjRLSVNTOVNPVVdQY0FvMHA1ZGpLY3doS0JjIn19..fSMnj1sMxZFcL9AwG7FmUw.jiSau5cf_I7-Ve4y_u8ZRi3ABWVOBo7XNQoGwRE2xgPC50geedTKnrlhzmuscgThdoTbkeCw15pENTuz2Fd2RUkLHIO6M3unnihOddwEE5xEkOK4vOkh3ZQPEVUwoj5ELhieobT2np7G1IvquE5kijoVMENttDqzbbJR03FKshr9hHpWJR5_gwG5e1MWW0FHShEFctddLL13r_e80WihFtfLHaU4O_nIoaZzxrWZsmcbEkTg2JN0a7Yxqk8NlozYFY0fLAFsgfKw-uiJntiFw-v1kVTDmFY_QXpL9azdqyvez9_NmXkBn7iizxd-3tOyXLTO8TmOZfpb4sRWCD91Cg.hsC9nJMeGR_cOnn1HNuTLQ
