### Add Comments to an Article

POST {{host}}/api/articles/how-to-train-your-dragon-1/comments
Authorization: Token eyJhbGciOiJFQ0RILUVTIiwiZW5jIjoiQTEyOENCQy1IUzI1NiIsImtpZCI6bnVsbCwiY3R5IjoiSldUIiwiZXBrIjp7Imt0eSI6Ik9LUCIsImNydiI6IlgyNTUxOSIsIngiOiJYZWxVQ0xQdjlfdkRDalJjVlN4cFdvaVc4MHI4Wkg4VU53NGpoUnpVTUZvIn19..lJ7yniDbdqzG5vGVAVhNzA.UI3_CHzBQvDZVKa1ZKanjxkfKTAdoPYAOy-xJOIYCSOeARKmV7-eXGO5yVg3rVNxTF08eVVb8w4p6RrJzq08gkBLi3Hr3lapqXXPrkdEMHtUWNBGO9H2G3aWjHanyg55yofnBeeUkiTfgWDUu22vctAZ9hpQKzohq9g9heovqAFNeGnHLdy8ZIO_L2JUsWIb9mDyME5K9nVHv03GogTEoZl6s1yAzOZqTQru8_kQ2_nvoRMBxT4j_4WVTngzozb-BKNqlPOvHsZwpgpem7rdkD763eDJtva8p63ypwoGLi4QGbt0QrVuJ-U7Ty165h16SZEVlsRCZSjGCod9YX9RBA.fNfUBQr7YxvfYew5CrEykw
Content-Type: application/stream+json

{
  "comment": {
    "body": "His name was my name too."
  }
}

### Get Comments from an Article, no Authorization

GET {{host}}/api/articles/how-to-train-your-dragon-1/comments

### Get Comments from an Article, Authorization

GET {{host}}/api/articles/how-to-train-your-dragon-1/comments
Authorization: Token eyJhbGciOiJFQ0RILUVTIiwiZW5jIjoiQTEyOENCQy1IUzI1NiIsImtpZCI6bnVsbCwiY3R5IjoiSldUIiwiZXBrIjp7Imt0eSI6Ik9LUCIsImNydiI6IlgyNTUxOSIsIngiOiJhV0E4M0UyWjNKdjZwd3o1MUhBRTloUWxJNmRiZnlhaTRiOWQzX0p3bmlvIn19..j5M1Q4kDo6LIgBsiDZ3cLA.wuo-EBDXKkAujGEStGuBUicjhwN_3NBDwAuhpoMCt7AgogZyuMXArMKvGovV7BKvvSQ9xCfvo2rZJXYgvOJE0XUPef9oK90Ao85jezJguUdlamN0MLu6OGiQcO3KhjZaqqwaz9UUe18q8NI6cMh99NLUXkoycwrKsZdxfiQYa7B97YjdYXPySIWjT4eEuv4uMHNiObdwaq5T0ICwuN5fZ4ZqS-_c203BgHSRDW_Wzq7846Fl4YzUTpCSGvSlniAy1hzsRh30YNDK1BbABQqSO-n9ob7OdELOivE1Ti9A2DLTeDZ1-0EpK3BVse0SiIs4V-weOSegiTnVpX4jWiL_Lw.sELEKEp3sAh7R6PHap30-Q

### Delete Comment

DELETE {{host}}/api/articles/how-to-train-your-dragon-1/comments/1
Authorization: Token eyJhbGciOiJFQ0RILUVTIiwiZW5jIjoiQTEyOENCQy1IUzI1NiIsImtpZCI6bnVsbCwiY3R5IjoiSldUIiwiZXBrIjp7Imt0eSI6Ik9LUCIsImNydiI6IlgyNTUxOSIsIngiOiJYZWxVQ0xQdjlfdkRDalJjVlN4cFdvaVc4MHI4Wkg4VU53NGpoUnpVTUZvIn19..lJ7yniDbdqzG5vGVAVhNzA.UI3_CHzBQvDZVKa1ZKanjxkfKTAdoPYAOy-xJOIYCSOeARKmV7-eXGO5yVg3rVNxTF08eVVb8w4p6RrJzq08gkBLi3Hr3lapqXXPrkdEMHtUWNBGO9H2G3aWjHanyg55yofnBeeUkiTfgWDUu22vctAZ9hpQKzohq9g9heovqAFNeGnHLdy8ZIO_L2JUsWIb9mDyME5K9nVHv03GogTEoZl6s1yAzOZqTQru8_kQ2_nvoRMBxT4j_4WVTngzozb-BKNqlPOvHsZwpgpem7rdkD763eDJtva8p63ypwoGLi4QGbt0QrVuJ-U7Ty165h16SZEVlsRCZSjGCod9YX9RBA.fNfUBQr7YxvfYew5CrEykw

